version: '3.8'

services:
  # Prometheus - Time-series database that scrapes metrics from Flowplane
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: flowplane-prometheus
    ports:
      - "9091:9090"  # Expose on 9091 to avoid conflict with Flowplane metrics port
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    # For Linux: map host.docker.internal to host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - flowplane-monitoring
    restart: unless-stopped

  # Grafana - Visualization dashboard for metrics
  grafana:
    image: grafana/grafana:10.2.2
    container_name: flowplane-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=
    networks:
      - flowplane-monitoring
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:

networks:
  flowplane-monitoring:
    driver: bridge
