openapi: 3.0.0
info:
  title: Custom Response Filter Demo
  version: 1.0.0

servers:
  - url: https://httpbin.org

x-flowplane-filters:
  - filter:
      type: custom_response
  - filter:
      type: cors
      policy:
        allow_origin:
          - type: exact
            value: "*"
        allow_methods:
          - GET
        allow_headers:
          - content-type
        max_age: 3600

paths:
  /status/200:
    get:
      summary: Success response
      responses:
        '200':
          description: Success

  /status/400:
    get:
      summary: Bad request with custom response
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /status/500:
    get:
      summary: Server error with custom response
      responses:
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check with custom_response disabled
      x-flowplane-route-overrides:
        custom_response: disabled
      responses:
        '200':
          description: OK

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        status_code:
          type: integer
        message:
          type: string
