# Prometheus configuration for Flowplane monitoring
global:
  scrape_interval: 15s      # Scrape metrics every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  external_labels:
    monitor: 'flowplane-monitor'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # Flowplane control plane metrics
  - job_name: 'flowplane'
    static_configs:
      # Use service name from docker-compose network
      - targets: ['control-plane:9090']
        labels:
          service: 'flowplane-control-plane'
          component: 'api'

    # Scrape metrics every 10 seconds for real-time monitoring
    scrape_interval: 10s
    scrape_timeout: 5s

    # Relabel to add useful metadata
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'flowplane-control-plane'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
