import { defineConfig, devices } from '@playwright/test';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Auth state files saved by setup projects (OIDC browser sessions)
const adminAuthFile = join(__dirname, 'playwright', '.auth', 'admin.json');
const orgadminAuthFile = join(__dirname, 'playwright', '.auth', 'orgadmin.json');

/**
 * Playwright configuration for Flowplane E2E tests.
 *
 * Prerequisites:
 *   - `make up` must be running (Flowplane CP + PostgreSQL + Zitadel)
 *   - `make seed` must have run (creates demo org, users, and teams)
 *   - `.env.zitadel` must exist (generated by setup-zitadel.sh, contains ZITADEL_ADMIN_PAT)
 *
 * Auth setup projects use real Zitadel OIDC login via browser automation.
 * They set test user passwords via Zitadel Management API, then navigate
 * through the Zitadel hosted login page to obtain OIDC sessions.
 *
 * Test project routing:
 *   - `admin`    → platform admin auth → admin-pages, resource-pages, smoke tests
 *   - `orgadmin` → org admin auth → orgadmin tests, agent/team/member/route/resource CRUD
 *   - `noauth`   → no auth state → auth.test.ts (login flow tests)
 *   - `enforce`  → no project-level auth → permission-enforcement tests (use per-test storageState)
 */
export default defineConfig({
	testDir: './e2e',
	fullyParallel: false,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 0,
	workers: process.env.CI ? 1 : undefined,
	reporter: [['list'], ['html', { open: 'never' }]],
	use: {
		baseURL: process.env.BASE_URL || 'http://localhost:8080',
		trace: 'on-first-retry',
		// OIDC redirects through Zitadel can be slow
		actionTimeout: 15000,
		navigationTimeout: 30000
	},
	// Increase global timeout for OIDC flows
	timeout: 60000,
	projects: [
		// ── Setup ──────────────────────────────────────
		{
			name: 'setup',
			testMatch: /auth\.setup\.ts/
		},
		// setup-orgadmin runs later (as setup-orgadmin-fresh) after admin/noauth
		// to ensure its Zitadel session isn't invalidated by other OIDC flows

		// ── Platform admin tests ───────────────────────
		{
			name: 'admin',
			use: {
				...devices['Desktop Chrome'],
				storageState: adminAuthFile
			},
			dependencies: ['setup'],
			testMatch: /(admin-pages|resource-pages|smoke)\.test\.ts/
		},

		// ── Auth flow tests (no pre-existing session) ──
		// Runs alongside admin tests (no auth state to invalidate)
		{
			name: 'noauth',
			use: {
				...devices['Desktop Chrome'],
				storageState: { cookies: [], origins: [] }
			},
			dependencies: ['setup'],
			testMatch: /auth\.test\.ts/
		},

		// ── Re-authenticate orgadmin after admin/noauth tests ──
		// Admin tests and noauth login flows can invalidate the orgadmin
		// Zitadel session server-side. Re-running setup ensures a fresh session.
		{
			name: 'setup-orgadmin-fresh',
			testMatch: /orgadmin\.setup\.ts/,
			dependencies: ['admin', 'noauth']
		},

		// ── Org admin tests ────────────────────────────
		// Depend on fresh orgadmin setup to guarantee valid Zitadel session
		{
			name: 'orgadmin',
			use: {
				...devices['Desktop Chrome'],
				storageState: orgadminAuthFile
			},
			dependencies: ['setup-orgadmin-fresh'],
			testMatch: /(orgadmin|agents|teams|members|resource-crud|routes|org-context)\.test\.ts/
		},

		// ── Permission enforcement tests ───────────────
		// Runs after orgadmin tests
		{
			name: 'enforce',
			use: {
				...devices['Desktop Chrome'],
				storageState: orgadminAuthFile
			},
			dependencies: ['orgadmin'],
			testMatch: /permission-enforcement\.test\.ts/
		}
	],
	webServer: {
		command: './target/debug/flowplane',
		cwd: join(__dirname, '..'),
		url: 'http://localhost:8080/api/v1/auth/config',
		timeout: 30_000,
		reuseExistingServer: !process.env.CI,
		env: {
			FLOWPLANE_DATABASE_URL: 'postgresql://flowplane:flowplane@localhost:5432/flowplane',
			FLOWPLANE_DATABASE_AUTO_MIGRATE: 'true',
			FLOWPLANE_COOKIE_SECURE: 'false',
			FLOWPLANE_API_PORT: '8080',
			FLOWPLANE_API_BIND_ADDRESS: '127.0.0.1',
			FLOWPLANE_UI_ORIGIN: 'http://localhost:8080',
			RUST_LOG: 'warn,flowplane=info'
		},
		stdout: 'pipe',
		stderr: 'pipe'
	}
});
