import { test as setup, expect } from '@playwright/test';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { readFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const authFile = join(__dirname, '..', 'playwright', '.auth', 'admin.json');

// Platform admin credentials (must match docker-compose.yml FLOWPLANE_SUPERADMIN_EMAIL)
const ADMIN_EMAIL = process.env.E2E_ADMIN_EMAIL ?? 'admin@flowplane.local';
const ADMIN_PASSWORD = 'E2eAdmin!SecurePass1';

// Zitadel API configuration
const ZITADEL_HOST = process.env.ZITADEL_HOST ?? 'http://localhost:8081';

/**
 * Load the Zitadel admin PAT from .env.zitadel or environment.
 * This PAT is generated by `scripts/setup-zitadel.sh` during `make up`.
 */
function loadZitadelPat(): string {
	// Prefer environment variable
	if (process.env.ZITADEL_ADMIN_PAT) {
		return process.env.ZITADEL_ADMIN_PAT;
	}
	// Fall back to .env.zitadel file
	const envPath = join(__dirname, '..', '..', '.env.zitadel');
	try {
		const content = readFileSync(envPath, 'utf-8');
		for (const line of content.split('\n')) {
			const match = line.match(/^ZITADEL_ADMIN_PAT=(.+)$/);
			if (match) {
				return match[1].trim();
			}
		}
	} catch {
		// File not found — fall through to error
	}
	throw new Error(
		'ZITADEL_ADMIN_PAT not found. Run `make up` first to generate .env.zitadel, ' +
			'or set ZITADEL_ADMIN_PAT environment variable.'
	);
}

/**
 * Find a Zitadel user by email and return their user ID.
 */
async function findZitadelUserId(pat: string, email: string): Promise<string> {
	const resp = await fetch(`${ZITADEL_HOST}/v2/users`, {
		method: 'POST',
		headers: {
			Authorization: `Bearer ${pat}`,
			'Content-Type': 'application/json'
		},
		body: JSON.stringify({
			queries: [{ emailQuery: { emailAddress: email } }]
		})
	});
	if (!resp.ok) {
		throw new Error(`Zitadel user search failed (${resp.status}): ${await resp.text()}`);
	}
	const data = (await resp.json()) as {
		result?: Array<{ userId?: string; id?: string }>;
	};
	const userId = data.result?.[0]?.userId ?? data.result?.[0]?.id;
	if (!userId) {
		throw new Error(`Zitadel user not found: ${email}`);
	}
	return userId;
}

/**
 * Set password for a Zitadel user via the Management API.
 * Uses `changeRequired: false` to skip forced password change on login.
 */
async function setZitadelPassword(pat: string, userId: string, password: string): Promise<void> {
	const resp = await fetch(`${ZITADEL_HOST}/v2/users/${userId}/password`, {
		method: 'POST',
		headers: {
			Authorization: `Bearer ${pat}`,
			'Content-Type': 'application/json'
		},
		body: JSON.stringify({
			newPassword: { password, changeRequired: false }
		})
	});
	if (!resp.ok) {
		throw new Error(`Failed to set Zitadel password (${resp.status}): ${await resp.text()}`);
	}
}

/**
 * Complete the Zitadel OIDC login flow in the browser.
 *
 * Flow: app /login → click "Sign in with Zitadel" → Zitadel login page →
 *       fill username → next → fill password → submit → redirect back to app
 */
async function performOidcLogin(
	page: import('@playwright/test').Page,
	email: string,
	password: string
): Promise<void> {
	// Navigate to the app login page
	await page.goto('/login');

	// Click "Sign in with Zitadel" to initiate OIDC redirect
	await page.getByRole('button', { name: /sign in/i }).click();

	// Wait for Zitadel login page to load (cross-origin redirect)
	await page.waitForURL(/localhost:8081\/ui\/login/, { timeout: 15000 });

	// Step 1: Fill username (loginName) and submit
	await page.locator('#loginName').fill(email);
	await page.locator('#submit-button').click();

	// Step 2: Fill password and submit
	await page.locator('#password').waitFor({ state: 'visible', timeout: 10000 });
	await page.locator('#password').fill(password);
	await page.locator('#submit-button').click();

	// Step 3: Handle optional Zitadel MFA setup prompt (click "Skip" if shown)
	const skipButton = page.getByRole('button', { name: 'Skip' });
	try {
		await skipButton.waitFor({ state: 'visible', timeout: 5000 });
		await skipButton.click();
	} catch {
		// No MFA prompt — Zitadel redirected directly
	}

	// Wait for OIDC redirect back to the app and navigation to dashboard
	await page.waitForURL(/\/dashboard/, { timeout: 30000 });
	await expect(page.locator('body')).toBeVisible();
}

setup('authenticate as platform admin', async ({ page }) => {
	const pat = loadZitadelPat();

	// Ensure the admin user has a known password for this test run
	console.log('[auth-setup] Setting admin password via Zitadel API...');
	const userId = await findZitadelUserId(pat, ADMIN_EMAIL);
	await setZitadelPassword(pat, userId, ADMIN_PASSWORD);
	console.log(`[auth-setup] Password set for ${ADMIN_EMAIL} (userId: ${userId})`);

	// Perform real OIDC login via browser
	console.log('[auth-setup] Starting OIDC login flow...');
	await performOidcLogin(page, ADMIN_EMAIL, ADMIN_PASSWORD);
	console.log('[auth-setup] OIDC login complete, saving browser state');

	// Save storage state (cookies + localStorage with OIDC tokens)
	await page.context().storageState({ path: authFile });
});
